# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-29 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=250)),
                ('board_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_title', models.CharField(max_length=250)),
                ('response_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=250)),
                ('tag_votes', models.IntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('phrase_text', models.CharField(max_length=250)),
                ('phrase_votes', models.IntegerField(default=0)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='search.Response')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Board')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Board'),
        ),
    ]
