# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-29 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='phrase_text',
            new_name='phrase_title',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response_title',
        ),
        migrations.AddField(
            model_name='response',
            name='response_text',
            field=models.CharField(default='default', max_length=1000),
        ),
    ]
